//ActionTypes.js 真正改动了数据的 actionType 在这里
export const ADD_ITEM = 'ADD_ITEM'

// auth.js
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const TITLE_INFO = 'TITLE_INFO';
export const CURRENT_USER_REQUEST = 'CURRENT_USER_REQUEST';
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';

//user.js
export const QUERY_USERS = 'QUERY_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const DEL_USER = 'DEL_USER';
export const DEL_USER_SUCCESS = 'DEL_USER_SUCCESS';
export const POST_ADD_USER = 'POST_ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const DATA_LIST = 'DATA_LIST';

//menu
export const MENU_LIST = 'MENU_LIST';

// classFlight.js
export const QUERY_CLASSFLIGHT = 'QUERY_CLASSFLIGHT';
export const RECEIVE_CLASSFLIGHT = 'RECEIVE_CLASSFLIGHT';
export const DEL_CLASSFLIGHT = 'DEL_CLASSFLIGHT';
export const DEL_CLASSFLIGHT_SUCCESS = 'DEL_CLASSFLIGHT_SUCCESS';
export const POST_ADD_CLASSFLIGHT = 'POST_ADD_CLASSFLIGHT';
export const ADD_CLASSFLIGHT_SUCCESS = 'ADD_CLASSFLIGHT_SUCCESS';
export const EDIT_CLASSFLIGHT_SUCCESS = 'EDIT_CLASSFLIGHT_SUCCESS';
export const CLASSFLIGHT_LIST = 'CLASSFLIGHT_LIST';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';

export const DELETE_ALL_CLASSFLIGHT = 'DELETE_ALL_CLASSFLIGHT';
export const DELETE_ALL_CLASS_SUCCESS = 'DELETE_ALL_CLASS_SUCCESS';
export const QUERY_CLASSPACKAGE = 'QUERY_CLASSPACKAGE';